name: Bug Report
description: 'File a bug report.'
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: bug-reproduction
    attributes:
      label: Steps to reproduce the behavior
      placeholder: A list of steps to reproduce the described bug.
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: How are you using MagicPH?
      multiple: true
      options:
        - Extension
        - Userscript
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: URL
      description: What URL are you attempting to access? If you do not wish to disclouse, put the URL of this GitHub repository [https://github.com/magicoflolis/Magic-PH](https://github.com/magicoflolis/Magic-PH).
    validations:
      required: true